/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/oEv4OBf0M5j
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { JSX, SVGProps } from "react"

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export default  function HeroSection() {
  return (
    <div>
      
  <section className="w-full ">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl lg:text-5xl/none">Inventory Management</h1>
            <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Manage your inventory with ease. Keep track of stock, fulfill orders, and generate reports.
            </p>
          </div>
        </div>
        <div className=" mt-10 grid max-w-[900px] gap-6 mx-auto lg:grid-cols-3 lg:gap-10">
          <div className="flex flex-col items-center space-y-2 text-center">
            <div className="flex items-center justify-center w-12 h-12 rounded-full border border-gray-200 border-gray-200 bg-gray-50 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950">
              <WarehouseIcon className="w-6 h-6 text-gray-400 dark:text-gray-400" />
            </div>
            <h3 className="text-xl font-semibold">Inventory Tracking</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">Keep track of stock levels</p>
          </div>
          <div className="flex flex-col items-center space-y-2 text-center">
            <div className="flex items-center justify-center w-12 h-12 rounded-full border border-gray-200 border-gray-200 bg-gray-50 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950">
              <ListOrderedIcon className="w-6 h-6 text-gray-400 dark:text-gray-400" />
            </div>
            <h3 className="text-xl font-semibold">Order Management</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">Fulfill and track orders</p>
          </div>
          <div className="flex flex-col items-center space-y-2 text-center">
            <div className="flex items-center justify-center w-12 h-12 rounded-full border border-gray-200 border-gray-200 bg-gray-50 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950">
              <PieChartIcon className="w-6 h-6 text-gray-400 dark:text-gray-400" />
            </div>
            <h3 className="text-xl font-semibold">Reporting</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">Generate sales and inventory reports</p>
          </div>
        </div>
      </div>
    </section>

    </div>


  )
}

function ListOrderedIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="10" x2="21" y1="6" y2="6" />
      <line x1="10" x2="21" y1="12" y2="12" />
      <line x1="10" x2="21" y1="18" y2="18" />
      <path d="M4 6h1v4" />
      <path d="M4 10h2" />
      <path d="M6 18H4c0-1 2-2 2-3s-1-1.5-2-1" />
    </svg>
  )
}


function PieChartIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.21 15.89A10 10 0 1 1 8 2.83" />
      <path d="M22 12A10 10 0 0 0 12 2v10z" />
    </svg>
  )
}


function WarehouseIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 8.35V20a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V8.35A2 2 0 0 1 3.26 6.5l8-3.2a2 2 0 0 1 1.48 0l8 3.2A2 2 0 0 1 22 8.35Z" />
      <path d="M6 18h12" />
      <path d="M6 14h12" />
      <rect width="12" height="12" x="6" y="10" />
    </svg>
  )
}
